#!/bin/python

# Head ends here
def remove_possibilities(a):
  change = True
  while change:
    change = False
    for i in range(9):
        for j in range(9):
          if(len(a[i][j])>1):
            x,y=3*(i/3),3*(j/3)
            vals=a[i][:]+[row[j] for row in a]+[a[x][y],a[x+1][y],a[x+2][y],a[x][y+1],a[x+1][y+1],a[x+2][y+1],a[x][y+2],a[x+1][y+2],a[x+2][y+2]]
            #print "the main grid is"
            #print a
            #print "vals is"
            #print vals
            vals[:]=(value for value in vals if len(value)==1)
            for value in vals:
              if(value[0] in a[i][j]):
                change=True
                a[i][j].remove(value[0])

def find_singleton(a):
  for i in range(9):
    j = 0
    row = a[i][:]
    col=[row[i] for row in a]
    row = a[i][:]
    x,y=3*(i/3),3*(i%3)
    box = [a[x][y],a[x][y+1],a[x][y+2],a[x+1][y],a[x+1][y+1],a[x+1][y+2],a[x+2][y],a[x+2][y+1],a[x+2][y+2]]
    freq=[0,0,0,0,0,0,0,0,0,0]
    for elems in row:
      if(len(elems)>1):
        for elem in elems:
          freq[elem]+=1
    if( 1 in freq):
      index = freq.index(1)
      for elems in row:
          if index in elems:
            a[i][j]=[index];
            remove_possibilities(a)
            return;
          j=j+1;
    freq=[0,0,0,0,0,0,0,0,0,0]
    for elems in col:
      if(len(elems)>1):
        for elem in elems:
          freq[elem]+=1
    if( 1 in freq):
      index = freq.index(1)
      for elems in col:
          if index in elems:
            a[j][i]=[index];
            remove_possibilities(a)
            return;
          j=j+1;
    freq=[0,0,0,0,0,0,0,0,0,0]
    for elems in box:
      if(len(elems)>1):
        for elem in elems:
          freq[elem]+=1
    if( 1 in freq):
      index = freq.index(1)
      for elems in box:
        if index in elems:
           a[x+(j/3)][y+(j%3)]=[index];
           remove_possibilities(a)
           return;
      j=j+1;
  return

def clean(grid):

  remove_possibilities(grid)
  condition=True
  for i in range(9):
    for j in range(9):
      if(len(grid[i][j])==0):
         print "a contradiction found in upper one ",i,j
         print grid
         print "end of grid"
         return False
  while condition == True:
    condition = False
    init_grid=grid[:]
    find_singleton(grid)
    if(init_grid==grid):
      print "noo changes"
      break
    print "yoo changes"
    for i in range(9):
      for j in range(9):
        print "printing grid in clean"
        print grid[i][j]
        if(len(grid[i][j])==0):
           print "a contradiction found in lower ones"
           return False
    condition = True
  return grid

def sudoku_solve(grid):

  clean(grid)
  if all(len(grid[i/9][i%9]) == 1 for i in range(81)):
    print "Solved it"
    return grid

  n,i = min( (len(grid[i/9][i%9]),i) for i in range(81) if len(grid[i/9][i%9]) > 1)
  print grid
  print n,i,grid[i/9][i%9]

  for d in grid[i/9][i%9]:
    print "assigning ",d," to ",i
    temp_grid = grid[:]
    temp_grid[i/9][i%9]=[d]
    seq = list();
    if( clean(temp_grid) != False):
      seq.append(sudoku_solve(temp_grid))
    else:
      print "grid is false while assigning ",d," to ",i
 
  print "seq for ",n,i,grid[i/9][i%9]," is ", seq
  for e in seq:
    if e: return e
  return False;

# Tail starts here
n = input()

for temp in range(n):
    board = []
    for j in range(9):
        board.append([int(k) for k in raw_input().split()])
    for k in range(9):
        for l in range(9):
          if board[k][l]==0:
            board[k][l]=[1,2,3,4,5,6,7,8,9]
          else:
            board[k][l]=[board[k][l]]
    sudoku_solve(board)
    for i in range(9):
      print board[i][0],board[i][1],board[i][2],board[i][3],board[i][4],board[i][5],board[i][6],board[i][7],board[i][8]
